name: Run Lighthouse plugin on Linux
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install sitespeed.io
      run: |
        npm install sitespeed.io -g
        cd ../plugin-css
        npm install
    - name: Lint
      run: npm run lint
    - name: Show sitespeed.io version
      run: sitespeed.io --version
    - name: Run tests using css plugin
      run: sitespeed.io --plugins.add ./lib/index.js https://www.sitespeed.io/
 